### ---------------------- AUTH ----------------------
# @name register

@userId = {{register.response.body.userId}}
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Usuario Padrao Formacao",
  "email": "usuarioformacao@formacao.dev",
  "password": "#Senha123"
}

###
# @name login
@token = {{login.response.body.token}}
@userId = {{login.response.body.userId}}

POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "usuarioformacao@formacao.dev",
  "password": "#Senha123"
}


### ------------------ MARKET ------------------

### ------------------ CREATE MARKET ------------------

# @name create
@uuidMarket = {{create.response.body.id}}

POST http://localhost:4000/market
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bistek",
  "userId": "86fc5d42-4221-42fe-bd27-337a420f0eb5"
}

### ------------------ GET MARKETS -----------------------
GET http://localhost:4000/market
Content-Type: application/json
Authorization: Bearer {{token}}

###

### ------------------ GET MARKET BY ID ------------------
GET http://localhost:4000/market/1333043d-3952-44c0-ba47-dccd3d3ee929
Content-Type: application/json
Authorization: Bearer {{token}}

###

### ------------------ UPDATE MARKET ------------------
PATCH http://localhost:4000/market/1333043d-3952-44c0-ba47-dccd3d3ee929
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bistek Atualizado"
}

###

### ------------------ DELETE MARKET ------------------
DELETE http://localhost:4000/market/1333043d-3952-44c0-ba47-dccd3d3ee929
Content-Type: application/json
Authorization: Bearer {{token}}

###



### ---------------------- PRODUCT --------------------------

### ------------------ CREATE PRODUCT ------------------
# @name create
@uuidProduct = 1dbc045a-712e-4489-95c0-2a77b3f7a202
@userId = 8460086d-b156-451c-9734-486fbdef69cb

POST http://localhost:4000/product
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Macarrão",
  "brand": "Gallo",
  "listDefault": true,
  "userId": "86fc5d42-4221-42fe-bd27-337a420f0eb5"
}

###

### ------------------ GET PRODUCT BY ID ------------------
GET http://localhost:4000/product/e254d13e-6a3c-43d0-b9ff-f501f16a6d34
Content-Type: application/json
Authorization: Bearer {{token}}

###

### ----------------- GET PRODUCTS BY NAME ------------------
GET http://localhost:4000/product/search?name=Feijão
Content-Type: application/json
Authorization: Bearer {{token}}

###

### ----------------- GET PRODUCTS BY BRAND ------------------
GET http://localhost:4000/product?brand=Feijão
Content-Type: application/json
Authorization: Bearer {{token}}

###

### ----------------- GET PRODUCTS BY LIST DEFAULT ------------------
GET http://localhost:4000/product/default?userId={{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

### ----------------- GET PRODUCTS BY USER ID ------------------
GET http://localhost:4000/product?userId={{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

### ----------------- UPDATE PRODUCT ------------------
PATCH http://localhost:4000/product/e254d13e-6a3c-43d0-b9ff-f501f16a6d34
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "brand": "Ligeirinho"
}

### 

### ----------------- DELETE PRODUCT ------------------

DELETE http://localhost:4000/product/{{uuidProduct}}
Content-Type: application/json
Authorization: Bearer {{token}}

### 

### ---------------------- PURCHASE --------------------------

### ------------------ CREATE PURCHASE ------------------
# @name create
@uuidMarket = 313bfd3a-092e-4ad2-ad78-e3e69a99fa9b
@userId = 86fc5d42-4221-42fe-bd27-337a420f0eb5

POST http://localhost:4000/purchase
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Compra de Janeiro",
  "userId": "{{userId}}",
  "marketId": "{{uuidMarket}}"
}

###

### ---------------------- PRODUCT ITEM --------------------------

### ------------------ CREATE PRODUCT ITEM ------------------
# @name create
@uuidProduct = b9548ec6-1bb7-44e4-b1b3-cb04f34cde6f
@uuidPurchase = d8e9da83-8f21-49c7-b46b-893170b41a50

POST http://localhost:4000/product-item
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": "{{uuidProduct}}",
  "purchaseId": "{{uuidPurchase}}",
  "price": 10.00,
  "amount": 1
}

###